-- MySQL Script generated by MySQL Workbench
-- Wed Mar 31 15:25:34 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inventoryDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inventoryDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventoryDB` DEFAULT CHARACTER SET utf8 ;
USE `inventoryDB` ;

-- -----------------------------------------------------
-- Table `inventoryDB`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventoryDB`.`category` ;

CREATE TABLE IF NOT EXISTS `inventoryDB`.`category` (
  `categoryID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL,
  PRIMARY KEY (`categoryID`),
  UNIQUE INDEX `CategoryID_UNIQUE` (`categoryID` ASC))
ENGINE = InnoDB;

-- --------------------------------------------------------


-- -----------------------------------------------------
-- Table `inventoryDB`.`inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventoryDB`.`inventory` ;

CREATE TABLE IF NOT EXISTS `inventoryDB`.`inventory` (
  `inventoryID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL,
  `description` VARCHAR(100) NULL,
  `itemCondition` VARCHAR(30) NULL,
  `location` VARCHAR(30) NULL,
  `categoryID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`inventoryID`),
  UNIQUE INDEX `InventoryID_UNIQUE` (`inventoryID` ASC),
  INDEX `CategoryID_idx` (`categoryID` ASC),
  CONSTRAINT `CategoryID`
    FOREIGN KEY (`categoryID`)
    REFERENCES `inventoryDB`.`category` (`categoryID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `inventoryDB`.`administrators`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventoryDB`.`administrators` ;

CREATE TABLE IF NOT EXISTS `inventoryDB`.`administrators` (
  `adminID` INT NOT NULL AUTO_INCREMENT,
  `emailAddress` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `firstName` VARCHAR(255) NULL,
  `lastName` VARCHAR(255) NULL,
  PRIMARY KEY (`adminID`),
  UNIQUE INDEX `adminID_UNIQUE` (`adminID` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- create the users and grant priveleges to those users
GRANT SELECT, INSERT, DELETE, UPDATE
ON inventoryDB.*
TO inv_user@localhost
IDENTIFIED BY '95yy$4wEZ*4e*2KZuD&hKx@bPMaG%Aoh&TG2';
